### PR TITLE
deps: regenerating with new Protobuf (6.4.4-sp)

### PR DESCRIPTION
**Pull request by suztomo**
To merge into 6.4.4-sp branch. This PR was generated using Protobuf 3.16.3. Source-Link: https://github.com/googleapis/googleapis/commit/3b236df084cf9222c529a2890f90e3a4ff0f2dfd

GraalVM tests are expected to fail because we didn't have GraalVM configuration file when 6.4.4 was released.

"ci / dependencies" are also expected to fail because the gRPC version 1.36 is not the latest version among dependency tree (1.37.0 is). As long as the library works with 1.36.3, it's fine.

### CODE REVIEW

**Comment by suztomo** [comment]
```
Warning:  Rule 2: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for io.grpc:grpc-api:1.36.3 paths to dependency are:
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-auth:1.36.3
    +-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-core:1.36.3
    +-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-protobuf:1.36.3
    +-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-stub:1.36.3
    +-io.grpc:grpc-api:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.api.grpc:grpc-google-common-protos:2.1.0
    +-io.grpc:grpc-api:1.36.3 (managed) <-- io.grpc:grpc-api:1.36.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.cloud:google-cloud-core-grpc:1.94.8
    +-io.grpc:grpc-api:1.36.3 (managed) <-- io.grpc:grpc-api:1.37.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.api.grpc:grpc-google-cloud-spanner-admin-instance-v1:6.4.4-sp.7-SNAPSHOT
    +-io.grpc:grpc-api:1.36.3 (managed) <-- io.grpc:grpc-api:1.37.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.api.grpc:grpc-google-cloud-spanner-v1:6.4.4-sp.7-SNAPSHOT
    +-io.grpc:grpc-api:1.36.3 (managed) <-- io.grpc:grpc-api:1.37.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.api.grpc:grpc-google-cloud-spanner-admin-database-v1:6.4.4-sp.7-SNAPSHOT
    +-io.grpc:grpc-api:1.36.3 (managed) <-- io.grpc:grpc-api:1.37.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-protobuf:1.36.3
    +-io.grpc:grpc-protobuf-lite:1.36.3
      +-io.grpc:grpc-api:1.36.3
, 
Require upper bound dependencies error for io.grpc:grpc-core:1.36.3 paths to dependency are:
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-core:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-netty-shaded:1.36.3
    +-io.grpc:grpc-core:1.36.3
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-com.google.cloud:google-cloud-core-grpc:1.94.8
    +-io.grpc:grpc-core:1.36.3 (managed) <-- io.grpc:grpc-core:1.37.0
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.opencensus:opencensus-contrib-grpc-util:0.30.0
    +-io.grpc:grpc-core:1.36.3 (managed) <-- io.grpc:grpc-core:1.27.2
and
+-com.google.cloud:google-cloud-spanner:6.4.4-sp.7-SNAPSHOT
  +-io.grpc:grpc-alts:1.36.3
    +-io.grpc:grpc-grpclb:1.36.3
      +-io.grpc:grpc-core:1.36.3
]
```

**Comment by suztomo** [comment]
Kokoro - Test: Integration — Build failed:

```
com.google.cloud.spanner.InstanceNotFoundException:
NOT_FOUND: com.google.cloud.spanner.InstanceNotFoundException: NOT_FOUND: io.grpc.StatusRuntimeException: NOT_FOUND: Instance not found: projects/gcloud-devel/instances/spanner-testing-west1
resource_type: "type.googleapis.com/google.spanner.admin.instance.v1.Instance"
resource_name: "projects/gcloud-devel/instances/spanner-testing-west1"
description: "Instance does not exist."

	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:279)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:181)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
	at com.google.cloud.spanner.testing.RemoteSpannerHelper.createTestDatabase(RemoteSpannerHelper.java:130)
	at com.google.cloud.spanner.testing.RemoteSpannerHelper.createTestDatabase(RemoteSpannerHelper.java:96)
	at com.google.cloud.spanner.connection.ITAbstractSpannerTest.setup(ITAbstractSpannerTest.java:222)

```

**Comment by suztomo** [comment]
Cherry-picked https://github.com/googleapis/java-spanner/pull/2028/commits/7b0443f97a95dc8aeadc389a771860e216c8f97b

**Comment by suztomo** [comment]
GraalVM tests are expected to fail because we didn't have GraalVM configuration file when 6.4.4 was released.

"ci / dependencies" are also expected to fail because the gRPC version 1.36 is not the latest version among dependency tree (1.37.0 is). As long as the library works with 1.36.3, it's fine.

**Comment by suztomo** [comment]
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error reading /root/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.1.0/proto-google-common-protos-2.1.0.jar; zip file is empty
[ERROR] error reading /root/.m2/repository/com/google/api/grpc/proto-google-common-protos/2.1.0/proto-google-common-protos-2.1.0.jar; zip file is empty
[ERROR] /tmpfs/src/github/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/SpannerInstanceAdminProto.java:[238,29] cannot find symbol
  symbol:   class AnnotationsProto
  location: package com.google.api
[ERROR] /tmpfs/src/github/java-spanner/proto-google-cloud-spanner-admin-instance-v1/src/main/java/com/google/spanner/admin/instance/v1/SpannerInstanceAdminProto.java:[239,29] cannot find symbol
  symbol:   class ClientProto
  location: package com.google.api
```

Artifact download error. Retrying.

**Comment by suztomo** [comment]
Integration test succeeded.

Screen Shot 2022-11-02 at 10 11 57 AM
